<?php
// $Id: watched_course.module,v 1.0.0.0 2012/11/16 10:48:52 lkuempel Exp $

/**
 * Implementation of hook_menu().
 */
function watched_course_menu() {
	$items['user/watched_course/%'] = array(
		'title' => "Watched Course",
		'page callback' => 'watched_course_set',
		'page arguments' => array(2),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	return $items;
}

function watched_course_set() {
	global $user;
	$sessid = arg(2);
	$sess_obj = watched_course_check_token($sessid);
	$_watched = watched_course_check($sess_obj->nid, $sess_obj->uid);
	if (!$_watched) {
		if ($sess_obj->nid && $sess_obj->uid) {
			$sql = "INSERT INTO {quiz_watched_course} (nid, uid) VALUES (%d, %d)";
			db_query($sql, $sess_obj->nid, $sess_obj->uid);
		}
	}
	watched_course_spend_token($sessid);
	exit;
}

function watched_course_check($nid=0, $uid=0) {
	global $user;
	if (!$nid) return FALSE;
	if (!$uid) $uid = $user->uid;
	
	$sql = 'SELECT * FROM {quiz_watched_course} WHERE nid=%d AND uid=%d';
	$watched_quiz = db_fetch_array(db_query($sql, $nid, $uid));
	if ($watched_quiz) return TRUE;
	return FALSE;
}

function watched_course_get_token($nid=0, $uid=0) {
	global $user;
	if (!$nid) return FALSE;
	if (!$uid) $uid = $user->uid;
	$sql = "SELECT * FROM {quiz_watched_course_sess} WHERE nid=%d AND uid=%d";
	$sess_obj = db_fetch_object(db_query($sql, $nid, $uid));
	if ($sess_obj->sessid) {
		return $sess_obj->sessid;
	}
	$sessid = md5($nid.$uid.time());
	$sql = "INSERT INTO {quiz_watched_course_sess} (nid, uid, sessid) VALUES (%d, %d, '%s')";
	db_query($sql, $nid, $uid, $sessid);
	return $sessid;
}

function watched_course_check_token($sessid) {
	$sql = "SELECT * FROM {quiz_watched_course_sess} WHERE sessid='%s'";
	return db_fetch_object(db_query($sql, $sessid));
}

function watched_course_spend_token($sessid) {
	$sql = "DELETE FROM {quiz_watched_course_sess} WHERE sessid='%s'";
	db_query($sql, $sessid);
}
